.editorconfig
.gitignore
CONTRIBUTING.md
Dockerfile
Jenkinsfile
NEWS.md
README.md
descriptors/DeploymentDescriptor-template.json
descriptors/ModuleDescriptor-template.json
docker/docker-entrypoint.sh
pom.xml
src/main/resources/log4j2.xml
src/test/resources/log4j2.xml

Added required boilerplate files for the project. The project will build.

Boilerplate for SIP2-2

---

Jenkinsfile

Update Jenkinsfile syntax to use true or false. (The yes|no is okay too.)

FOLIO-722 initial repo setup

---

NEWS.md
pom.xml

Added release notes to NEWS.md and incremented the version number to the next edge-sip2 version in the pom.

Releasing edge-sip2

---

NEWS.md
pom.xml

Updated NEWS.md to include two items for this bug fix release.

Tmp release 1.3.1

---

NEWS.md
pom.xml

Updated NEWS.md to contain the changes in v1.4.1

Release v1.4.1

---

NEWS.md
pom.xml

Tmp release 2.1.1

---

pom.xml

Log4j upgrade to 2.17 for edge modules

---

README.md

Co-authored-by: Wayne Schneider <wayne@indexdata.com>

README.md: Mount conf file to Docker container

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/edge/sip2/MainVerticle.java
src/main/java/org/folio/edge/sip2/handlers/HandlersFactory.java
src/main/java/org/folio/edge/sip2/modules/FolioResourceProviderModule.java
src/main/java/org/folio/edge/sip2/parser/Parser.java
src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java
src/test/java/org/folio/edge/sip2/api/support/BaseTest.java
src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java
src/test/java/org/folio/edge/sip2/handlers/CheckoutHandlerTests.java
src/test/java/org/folio/edge/sip2/handlers/EndPatronSessionHandlerTests.java
src/test/java/org/folio/edge/sip2/handlers/HandlersFactoryTests.java
src/test/java/org/folio/edge/sip2/handlers/LoginHandlerTests.java
src/test/java/org/folio/edge/sip2/handlers/PatronInformationHandlerTests.java
src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java
src/test/java/org/folio/edge/sip2/parser/ParserTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/DefaultResourceProviderTests.java
src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/FolioResourceProviderTests.java
src/test/java/org/folio/edge/sip2/repositories/LoginRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/PasswordVerifierTests.java
src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java

https://issues.folio.org/browse/SIP2-109

SIP2-109: Release 2.1.3

---

NEWS.md
pom.xml

edge-sip2: module release ( https://issues.folio.org/browse/SIP2-118 ) 
Release for the changes of : ( https://issues.folio.org/browse/SIP2-115 )

Tmp release 2.3.0

---

src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java

[SIP2-113](https://issues.folio.org/browse/SIP2-113)
Enhance Module Logging (multi tenant to include tenant id) : In a multi-tenant environment, I need a way to distinguish SIP2 logging between tenants so that I can accurately and quickly disambiguate SIP2 activity between tenants.
* changed log level in the log statement to print tenant id from session.
- Are the JIRAs under active development?   …

SIP2-113 : Enhance Module Logging (multi tenant to include tenant id

---

pom.xml

[MODINREACH-322](https://issues.folio.org/browse/MODINREACH-322)
Module Version Upgrade (for Nolana)
Below is a bump of module version upgrade (for Nolana) and as of now I think for inn-reach and sip2 we are not having release for Nolana, but if there is a release we want to push for Nolana like sip2 then do we bump the versions (Vert.x 4.3.4, micrometer 1.9.4, log4j 2.19.0, okapi 4.14.5), As per me maybe we should and then release the module for Nolana.. your thoughts please if we need (or not) bump these dependencies version.
Epic jira for Nolana - https://issues.folio.org/browse/FOLREL-553?src=confmacro -- These are the version upgrade needed Vert.x 4.3.4, micrometer 1.9.4, log4j 2.19.0, okapi 4.14.5, Update folio-spring-base from v2.. or v3.. to latest v5...
Version Upgrade changes …

MODINREACH-322

---

NEWS.md
pom.xml

SIP2-130 (https://issues.folio.org/browse/SIP2-130)
#Purpose
1. Make main branch sync with Nolana release 
#Approach
1. Update NEWS.md 
2. Update snapshot version

[SIP2-130] release for Nolana

---

PULL_REQUEST_TEMPLATE.md

As part of SIP2-128 added the new PULL_REQUEST_TEMPLATE.md file.

[SIP2-128] - Added new PULL_REQUEST_TEMPLATE.md

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/SIP2-138
Aligning with latest search module version 1.0.
Added 1.0 with existing versions of search in ModuleDescriptior-template.json file.

[SIP2-138] - Aligned search module with 1.0 

---

NEWS.md
README.md
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/test/java/org/folio/edge/sip2/api/support/TestUtils.java
src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java

This PR will take care of this scenario - If the location code is missing, then the error message will be "Configuration error: please add a value to Location Code."
In the code a check is made to determine if location code is null/empty then display this error message in logs and in the tool - 
"Configuration error: please add a value to Location Code." …

SIP2-94 - Adding indicative error message when location code is empty and SC status command is fired.

---

src/main/resources/templates/RenewResponse.ftl

https://issues.folio.org/browse/SIP2-147
It was noticed that in renew response the AB Item identifier required field was missing.
The implementation was done as part of [SIP2-121](https://issues.folio.org/browse/SIP2-121)
Added the missed out field in the renewresponse.ftl file
Ideally all of the PRs involved in breaking changes would be merged in the same …

[SIP2-147] - Adding missing item identifier in the renew response.

---

descriptors/ModuleDescriptor-template.json
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/resources/json/holds_requests_response.json
src/test/resources/json/recall_requests_response.json
src/test/resources/json/recall_requests_response1.json
src/test/resources/json/recall_requests_response2.json

Making changes to bring module in line with changes to circ interface (CIRC-253)

SIP2-148: updating circulation interface

---

src/main/java/org/folio/edge/sip2/domain/messages/responses/CheckinResponse.java
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/resources/templates/CheckinResponse.ftl
src/main/resources/templates/lib.ftl
src/test/java/org/folio/edge/sip2/domain/messages/responses/CheckinResponseTests.java
src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

To add extensions to the checkin response to allow kiosks to sort results
While it's helpful …

SIP2-145 - Add extensions for sorting into check-in response 

---

src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java

Correct an issue with the FeePaid repository that prevents successful requests from being made due to the username field not being populated.
The user object is already looked up by the FeePaid repository, so it's just matter of plucking the username from the returned result.
Ideally all of the PRs involved in breaking changes would be merged in the same …

SIP2-146 - Provision the username field for the account payment request

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java

[SIP2-153](https://issues.folio.org/browse/SIP2-153) : _Update to Java 17 edge-sip2_
Update the module to Java 17 and identify issues.
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
Changed the java sdk version to 17 wherever applicable

SIP2-153 : Update to Java 17 edge-sip2

---

src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java

To allow admins to properly set whether or not password verification should be required …

SIP2-154 - Disable forcing password verification on patron status endpoint

---

src/main/resources/templates/ItemInformationResponse.ftl
src/main/resources/templates/lib.ftl
src/test/java/org/folio/edge/sip2/handlers/ItemInformationHandlerTests.java

…ield not variable field notation
Correct misformed response field by change format of the fee type field to a fixed field from a variable length one.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

SIP2-156 - Correct template for item information

---

NEWS.md
README.md
pom.xml
src/main/java/org/folio/edge/sip2/MainVerticle.java
src/main/java/org/folio/edge/sip2/handlers/RenewHandler.java
src/main/java/org/folio/edge/sip2/handlers/freemarker/FreemarkerRepository.java
src/main/java/org/folio/edge/sip2/modules/ApplicationModule.java
src/main/java/org/folio/edge/sip2/parser/PatronInformationMessageParser.java
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/resources/templates/RenewResponse.ftl
src/test/java/org/folio/edge/sip2/domain/messages/requests/RenewTests.java
src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java

The purpose of this jira is to backport of renew command in Orchid.
Merged the PR of SIP2-121 and making it compatible for Orchid.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

SIP2-165 - SIP2: backport Renew command implementation in Orchid.

---

NEWS.md
README.md
pom.xml

To release renew command for Orchid.
Followed release procedure.
While it's helpful for …

Sip2 167 - Release for Orchid

---

NEWS.md
pom.xml
src/main/resources/templates/ItemInformationResponse.ftl
src/test/java/org/folio/edge/sip2/handlers/ItemInformationHandlerTests.java

To release orchid service patch 6 for sip2-161
Followed release instructions.
While it's …

Sip2 168 - Release Orchid service patch 6

---

pom.xml

Updated the version in pom for post release.
While it's helpful for reviewers to help …

[SIP2-168] - update version in pom post release

---

src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java

Don't fail configuration on missing sclocation, just warn

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml

Poppy Release
While it's helpful for reviewers to help identify potential problems, ensuring …

SIP2-170 - Poppy Release

---

descriptors/ModuleDescriptor-template.json

[MODFEE-337](https://issues.folio.org/browse/MODFEE-337) contains breaking changes in interface `feesfines`. Module edge-sip2 will not be affected by these changes, but it needs to declare support for the new interface version.
[SIP-171](https://issues.folio.org/browse/SIP2-171)
Ideally all of the PRs involved in breaking changes would be merged in the …

SIP-171: Add support for interface 'feesfines' version 19.0

---

src/main/java/org/folio/edge/sip2/domain/messages/enumerations/CurrencyType.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/resources/json/DefaultACSConfigurationNonDefaultedCurrency.json

Fix an issue with EUR not being detected as a valid currency.
While it's helpful for …

Add additional currency enum (including EUR)

---

src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/test/java/org/folio/edge/sip2/handlers/PatronStatusHandlerTests.java

SIP2-177 Do not populate status field of PatronStatus by default

---

src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/main/resources/templates/lib.ftl
src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java
src/test/resources/json/account_multiple_with_feefines_request_response.json

Fix issue with incomplete account data causing errors in patroninformation response
While …

SIP2-175 Filter accounts without barcodes out of patron info response

---

src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java

Sip2 180 - Fix rounding error in currency totals

---

src/main/java/org/folio/edge/sip2/repositories/PasswordVerifier.java
src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java

To return proper value for password verification in patron information requests, even if requiring patron password validation is disabled.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

SIP2-174 Refactor password verification code in patron info repo and add tests

---

src/main/java/org/folio/edge/sip2/domain/messages/PatronAccountInfo.java
src/main/java/org/folio/edge/sip2/domain/messages/responses/FeePaidResponse.java
src/main/java/org/folio/edge/sip2/domain/messages/responses/PatronInformationResponse.java
src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java
src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/main/resources/templates/FeePaidResponse.ftl
src/main/resources/templates/lib.ftl
src/test/java/org/folio/edge/sip2/domain/messages/PatronAccountInfoTest.java
src/test/java/org/folio/edge/sip2/domain/messages/responses/FeePaidResponseTests.java
src/test/java/org/folio/edge/sip2/domain/messages/responses/PatronInformationResponseTests.java
src/test/java/org/folio/edge/sip2/handlers/FeePaidHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java

Extend the fee paid handler for more granular information when paying on specific accounts.  …

SIP2-160 Extend Fee Paid Handler

---

README.md
descriptors/ModuleDescriptor-template.json

To solve the issue mentioned in the Jira SIP2-182
Added missing permissions in module descritor and readme file.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

[SIP2-182] - Added missing permissions.

---

src/main/java/org/folio/edge/sip2/repositories/PasswordVerifier.java
src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java

SIP2-174 Handle errors during patron login

---

pom.xml
src/test/java/org/folio/edge/sip2/api/support/BaseTest.java

To update the log4j version for Q release.
While it's helpful for reviewers to help identify …

Sip2 194 - Update log4j2 version

---

src/main/java/org/folio/edge/sip2/handlers/LoginHandler.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java
src/main/java/org/folio/edge/sip2/repositories/PasswordVerifier.java
src/main/java/org/folio/edge/sip2/repositories/domain/ExtendedUser.java
src/main/java/org/folio/edge/sip2/repositories/domain/User.java
src/main/java/org/folio/edge/sip2/session/SessionData.java
src/test/java/org/folio/edge/sip2/handlers/LoginHandlerTests.java

SIP2-192 Add call to configuration repo on login

---

src/main/java/org/folio/edge/sip2/MainVerticle.java
src/main/resources/log4j2.xml
src/test/resources/log4j2.xml

Sip2 184 - Add date and client IP to logs

---

README.md
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/main/java/org/folio/edge/sip2/session/SessionData.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java

Sip2 186 - Implement rejected checkin item status list

---

NEWS.md
pom.xml

Q release
While it's helpful for reviewers to help identify potential problems, ensuring …

Q release 3.2.0

---

NEWS.md
pom.xml

To release for Q SIP2-195
Release steps
While it's helpful for reviewers to help identify …

Sip2 197 - to release 3.2.1

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/main/resources/templates/CheckinResponse.ftl
src/main/resources/templates/lib.ftl
src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/resources/json/DefaultACSConfigurationNonDefaultedCurrency.json

Backport of SIP2-169 to 3.1.x branch
While it's helpful for reviewers to help identify …

Merge fix for 3.1.2

---

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

SIP2-173 Retrieve patron identifier (barcode) as part of checkin response

---

pom.xml

[SIP2-203] - Update version in master.

---

NEWS.md
pom.xml

To release 3.2.3

---

README.md
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/main/java/org/folio/edge/sip2/repositories/DefaultResourceProvider.java
src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java
src/main/java/org/folio/edge/sip2/repositories/IResourceProvider.java
src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java
src/main/java/org/folio/edge/sip2/repositories/UsersRepository.java
src/main/java/org/folio/edge/sip2/session/SessionData.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/FolioResourceProviderTests.java
src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java

https://folio-org.atlassian.net/browse/SIP2-89
While it's helpful for reviewers to help …

SIP2-89: Implement patron PIN field instead of patron password field 

---

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

Pull patron identifier from checkin response rather than requests query

---

src/main/java/org/folio/edge/sip2/repositories/UsersRepository.java

Fix endpoint for patron pin verification

---

src/main/java/org/folio/edge/sip2/utils/WebClientUtils.java

https://folio-org.atlassian.net/browse/SIP2-214

Disable verifyHost setting for WebClient

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/utils/WebClientUtils.java

T0 release 3.2.5

---

src/main/java/org/folio/edge/sip2/domain/messages/enumerations/CurrencyType.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/resources/json/DefaultACSConfigurationCopCurrency.json

To add support for COP currency as part of SIP2-219
The currency was added in the enum.
Patron information Command is working with response BH as COP as shown in the screenshot 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

[SIP2-219] - Add support for COP CurrencyType

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/repositories/LoginRepository.java

To release 3.2.7

---

src/main/resources/templates/lib.ftl

Make variableLengthListField template tolerant of empty members

---

pom.xml

[SIP2-233] - Upgrade the versions for Ramsons.

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Ramsons Release

---

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

To fix the issue as reported in https://folio-org.atlassian.net/browse/SIP2-231
The response place holder AJ is now set with item's title as expected.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

SIP2-231 - AJ Field (Title) Issue in Successful Renewals

---

src/main/java/org/folio/edge/sip2/MainVerticle.java
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

Add error handling for checkin when item is not found

---

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

The purpose of this PR is to fix the issue reported in https://folio-org.atlassian.net/browse/SIP2-232
The due date will be determined from the item;s loans data. If the item has no open loan then the due date will be set to null or blank. All the evidences are attached in the Jira.
Ideally all of the PRs involved in breaking changes would be merged in the …

SIP2-232 - AH Field (Due Date) Issue in Unsuccessful Renewals

---

src/main/java/org/folio/edge/sip2/domain/messages/enumerations/CurrencyType.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/resources/json/DefaultACSConfigurationZARCurrency.json

Add support for ZAR currency as per https://folio-org.atlassian.net/browse/SIP2-240
Added the support in CurrencyTypeM file and now ACS can be configured for this currency.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

[SIP2-240] - Add support for ZAR currency.

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/domain/messages/enumerations/CurrencyType.java
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/resources/json/DefaultACSConfigurationZARCurrency.json

To release 3.3.1

---

README.md
descriptors/ModuleDescriptor-template.json

Resolves: [SIP2-244](https://folio-org.atlassian.net/browse/SIP2-244)

SIP2-244 Update permission

---

pom.xml
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java

To fix the issue as stated in [SIP2-249](https://folio-org.atlassian.net/browse/SIP2-249) 
The item barcode has to be encoded and set as a literal value with double quotes to be identifiable and used for checkout and checkin operations.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

SIP2-249 - Encode the item barcode string as a literal value.

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/main/java/org/folio/edge/sip2/repositories/UsersRepository.java
src/main/java/org/folio/edge/sip2/utils/Utils.java
src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java
src/test/java/org/folio/edge/sip2/handlers/ItemInformationHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/FolioResourceProviderTests.java
src/test/java/org/folio/edge/sip2/repositories/LoginRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java
src/test/java/org/folio/edge/sip2/utils/UtilsTests.java

Release SIP2-249 and SIP2-252
While it's helpful for reviewers to help identify potential …

To release 3.2.8

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java
src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java
src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java
src/main/java/org/folio/edge/sip2/repositories/ItemRepository.java
src/main/java/org/folio/edge/sip2/repositories/UsersRepository.java
src/main/java/org/folio/edge/sip2/utils/Utils.java
src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java
src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java
src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java
src/test/java/org/folio/edge/sip2/utils/UtilsTests.java

To release 3.3.2

---

Dockerfile
Jenkinsfile
pom.xml

FOLIO-4214 - Java and RMB version upgrade

---

NEWS.md
src/main/java/org/folio/edge/sip2/parser/MessageParser.java
src/test/java/org/folio/edge/sip2/parser/CheckinMessageParserTests.java
src/test/java/org/folio/edge/sip2/parser/CheckoutMessageParserTests.java
src/test/java/org/folio/edge/sip2/parser/HoldMessageParserTests.java
src/test/java/org/folio/edge/sip2/parser/ItemInformationMessageParserTests.java
src/test/java/org/folio/edge/sip2/parser/ItemStatusUpdateMessageParserTests.java
src/test/java/org/folio/edge/sip2/parser/RenewMessageParserTests.java

https://folio-org.atlassian.net/browse/SIP2-98
Add removal of whitespaces for item barcode values.
- Trim parsed values for AB field
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

SIP2-98: Remove leading/trailing whitespaces for item barcodes

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java

Sunflower Bug fix R1 2025
https://folio-org.atlassian.net/browse/SIP2-275
While it's helpful …

Sunflower release 3.4.1

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/edge/sip2/MainVerticle.java

Make Health Check Port configurable by environment variable
add environment variable `HEALTH_CHECK_PORT`
[ SIP2-247](https://folio-org.atlassian.net/browse/SIP2-247)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

SIP2-247: Add environment variable for health check port

---

README.md
descriptors/ModuleDescriptor-template.json

Update for Split Search & Browse APIs
Update interfaces
While it's helpful for reviewers to …

SIP2-284: Update for Split Search & Browse APIs

---

NEWS.md
src/main/java/org/folio/edge/sip2/domain/messages/enumerations/CurrencyType.java
src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
src/test/resources/json/DefaultACSConfigurationMYRCurrency.json

To add MYR currency Type
Added a new currency Type `MYR`
[SIP2-276](https://folio-org.atlassian.net/browse/SIP2-276)
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._

SIP2-276: Add support for MYR CurrencyType
