src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/handlers/HandlersFactory.java, src/main/java/org/folio/edge/sip2/handlers/InvalidMessageHandler.java, src/main/java/org/folio/edge/sip2/parser/Parser.java, src/main/resources/templates/acs-status.ftl, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java, src/test/java/org/folio/edge/sip2/parser/ParserTests.java, src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
- Check that the Message output from the parser contains a checksum string, which indicates that Error Detection was enabled. If it was enabled, then check the validity of the checksum (performed by the parser).  If it's invalid, send message 96. 
- Wrapped the socket handler with a RecordParser so that it can take care of waiting for the ending delimiter.  This results in requiring all sip messages in tests to end in "\r".
- Able to set the IDE to use \r for carriage return. This effectively jumbled up the acs-status.ftl, as seen in the diff.
- Fixed checkstyle issues as encountered in files touched.
=> implemented Resend SC request

src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/domain/PreviousMessage.java, src/main/java/org/folio/edge/sip2/handlers/ACSResendHandler.java, src/main/java/org/folio/edge/sip2/handlers/HandlersFactory.java, src/main/java/org/folio/edge/sip2/handlers/ISip2RequestHandler.java, src/main/java/org/folio/edge/sip2/handlers/LoginHandler.java, src/main/java/org/folio/edge/sip2/handlers/SCStatusHandler.java, src/main/java/org/folio/edge/sip2/repositories/HistoricalMessageRepository.java, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/api/support/BaseTest.java, src/test/java/org/folio/edge/sip2/handlers/HandlersFactoryTests.java, src/test/java/org/folio/edge/sip2/handlers/freemarker/FreemarkerRepositoryTests.java, src/test/java/org/folio/edge/sip2/handlers/freemarker/FreemarkerUtilsTests.java, src/test/java/org/folio/edge/sip2/repositories/DefaultResourceProviderTests.java, src/test/java/org/folio/edge/sip2/repositories/HistoricalMessageRepositoryTests.java
Added a default method to ISip2RequestHandler to save the message to "session" so that it can be referenced in the next request.  This method is called by MainVerticle.  Ideally it should be silently invoked by each of the handler itself.  Only ACSResendHandler does not need to write its response to the session. 
"Session" is implemented as a static variable for now, which is available to all sessions :D. Will change it once the formal session implementation is merged in.
=> Implemented ACS Request Resend command (SIP2-12)

src/main/java/org/folio/edge/sip2/repositories/LoginRepository.java
The `sessionData` returned by `LoginRequestData.getSessionData()` is `null` as per the default implementation of `IRequestData`. Now we store the passed in session data in the request data and pass it to the provider.
=> Fix a NPE in the login repository

src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/handlers/CheckoutHandler.java, src/main/java/org/folio/edge/sip2/handlers/HandlersFactory.java, src/main/java/org/folio/edge/sip2/handlers/freemarker/FreemarkerRepository.java, src/main/java/org/folio/edge/sip2/modules/ApplicationModule.java, src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java, src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java, src/main/java/org/folio/edge/sip2/repositories/LoginRepository.java, src/main/java/org/folio/edge/sip2/repositories/Utils.java, src/main/resources/templates/CheckoutResponse.ftl, src/main/resources/templates/RenewResponse.ftl, src/main/resources/templates/lib.ftl, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/api/support/BaseTest.java, src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/CheckoutHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/HandlersFactoryTests.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/LoginRepositoryTests.java, src/test/resources/log4j2.xml
Added support for the checkout SIP2 command that allows edge-sip2 to receive this command, extract relevant data and send a FOLIO checkout request. This implementation also translates the FOLIO checkout response back into a SIP2 checkout response and returns this message to the client.
=> SIP2-47: Add checkout support to edge-sip2

src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/handlers/HandlersFactory.java, src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java, src/main/resources/DefaultACSConfiguration.json, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/api/support/BaseTest.java, src/test/java/org/folio/edge/sip2/api/support/TestUtils.java, src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/CheckoutHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/EndPatronSessionHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/HandlersFactoryTests.java, src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java
Assigned agreed upon values to the default ACS configuration file. 
Return UTC timestamp for transaction date instead of local (server) time. Adjusted tests upon making this change.
=> ACS Status default values

src/main/resources/templates/acs-status.ftl, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java
The timeout and retries fields are fixed length fields of 3 characters.  Currently it only displays a number "3" or "5" without any preceding 0's.  Modified the ACS status template to print out the numbers appropriately padded and modified the tests' expectations.
=> add zero padding to timeout and retries numbers

README.md, checkstyle.xml, src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/resources/log4j2.xml, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/api/support/BaseTest.java
Vertx already supports SSL/TLS but we need to be able to configure it. Now we allow startup config (JSON) to be passed to the existing `NetServerOptions` that can contain SSL specific options or any net server option if some other setting might be necessary. When not specified, SSL/TLS support is not enabled.
Also changed `log4j2.xml` to accept a system supplied variable to set the log level at runtime. To enable, pass `-Dloglevel=debug` (or whatever level) to the VM. The default level is "info".
Finally, added some config and security documentation to the README.md file.
=> SIP2-38: Add support for TLS (SSL) startup via vertx config

checkstyle.xml, src/main/java/org/folio/edge/sip2/MainVerticle.java, src/test/java/org/folio/edge/sip2/parser/ParserTests.java
Pass the timezone retrieved from FOLIO to the parser. This way transaction, return, hold expiration and due dates are assigned the proper offset when the received SIP date field does not contain timezone info.
=> Ensure the parser known which timezone is "local"

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/edge/sip2/modules/ApplicationModule.java, src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java, src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java, src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java, src/test/resources/json/manual_blocks_response.json, src/test/resources/json/no_manual_blocks_response.json
If the patron is invalid or blocked in some way, we will now return the patron status to reflect this and generic screen messages:
```
Your library card number cannot be located.  Please see a staff member for assistance.
There are unresolved issues with your account.  Please see a staff member for assistance.
```
=> SIP2-37: return proper patron status and screen messages

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
The self service kiosk being tested in Chalmers has a requirement that the title identifier (AJ) must be present in the SIP checkin response. However, this field is optional in SIP, so we ignored it to limit scope. This requirement was unknown and could not be known until actual integration testing.
We now add the title of the item into AJ field for the SIP checkin response. If title is not present, then we do not send it and the original error is shown in the kiosk. In this case, it is expected since there is likely a database problem here in that the title is not set in FOLIO.
=> SIP2-58: Add the title identifier (AJ) to the checkin response

README.md, pom.xml, src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/domain/PreviousMessage.java, src/main/java/org/folio/edge/sip2/metrics/Metrics.java, src/main/java/org/folio/edge/sip2/parser/Message.java, src/main/java/org/folio/edge/sip2/parser/Parser.java, src/test/java/org/folio/edge/sip2/metrics/MetricsTests.java, src/test/java/org/folio/edge/sip2/parser/ParserTests.java
Add support for Micrometer collection of metrics for delivery to a runtime defined backend. Micrometer claims to be the SLF4J for metrics, in that we code to a vendor agnostic API and rely on vendor specific bindings, that can be easily swapped in or out, to deliver metrics.
Also fixed a problem when bad data is received (the command was not being set to unknown).
Added a dependency analysis plugin for maven to better sort out dependencies (explicit vs implicit).
Added missing release maven plugin for when we do release.
Updated versions of dependencies. Note, we cannot update to Vert.x 3.7.1 unless one of these is done:
https://github.com/vert-x3/vertx-web/issues/1315
https://issues.folio.org/browse/SIP2-63
Added extensive documentation to the README for metrics setup and use.
=> SIP2-60: metrics for edge-sip2

pom.xml, src/main/java/org/folio/edge/sip2/handlers/EndPatronSessionHandler.java, src/main/java/org/folio/edge/sip2/modules/ApplicationModule.java, src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java, src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java, src/main/java/org/folio/edge/sip2/repositories/LoginRepository.java, src/main/java/org/folio/edge/sip2/repositories/PasswordVerifier.java, src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java, src/main/java/org/folio/edge/sip2/repositories/UsersRepository.java, src/main/java/org/folio/edge/sip2/repositories/domain/Address.java, src/main/java/org/folio/edge/sip2/repositories/domain/PatronPasswordVerificationRecords.java, src/main/java/org/folio/edge/sip2/repositories/domain/Personal.java, src/main/java/org/folio/edge/sip2/repositories/domain/User.java, src/main/java/org/folio/edge/sip2/session/SessionData.java, src/test/java/org/folio/edge/sip2/handlers/EndPatronSessionHandlerTests.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/LoginRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/PasswordVerifierTests.java, src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java, src/test/java/org/folio/edge/sip2/session/SessionDataTests.java, src/test/resources/json/user_response.json
We will now verify any command with a patron password sent if the tenant setting `patronPasswordVerificationRequired` is set to true. In this case, we attempt to log in to FOLIO. If we succeed, then the patron password is valid and the command can continue. If not, we shortcut the command and return a SIP2 message indicating command failure. If the setting is not true, then we do not attempt login and proceed with the command as usual.
SIP2-66 was also fixed here since end patron session sends a patron password.
SIP2-68 was also addressed in order to provide for a way to set the requirement for password verification.
=> SIP2-61: Enable PIN verification

src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java, src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java, src/test/resources/json/user_response_with_no_personal.json, src/test/resources/json/user_response_wo_personal_names.json
Added a simple check for empty user name string and assign the patron identifier if it's empty when building out a valid patron information response. 
Added one new test case for the code change, moved private utility methods to the bottom so all the tests are grouped together. If this proved too much headaches for reviewing I don't mind restoring the previous order.
=> SIP2-65: Return patron identifer when user name components are empty

src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java
A unit test started failing when daylight saving time ended in the
timezone used for a test since we were manually adjusting the clock by a
fixed offset to determine the expected date and time returned in a SIP
response. The offset is now 1 instead of 2, so the test will fail until
DST begins again in the timezone.
To correct this, since a master build shouldn't remain broken for
months, we'll just use java.time to compute the expected date and time
based on the test's timezone. This will handle DST shifts automatically.
=> SIP2-76: Fix unit test that uses fixed hours adjustment

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> SIP2-75 FOLIO-2358 manage container memory

descriptors/ModuleDescriptor-template.json
The `circulation` interface needs to be updated to `8.0` in order to
deploy Edelweiss.
=> SIP2-77: Add the circulation interface 8.0 version

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/SIP2-79: Migrate to new major version of item-storage, inventory, circulation.
Migrate to circulation v10. Changes:
Changes:
1. {{item.status.name}} has restricted to the following values:
* Available
* Awaiting pickup
* Awaiting delivery
* Checked out
* In process
* In transit
* Missing
* On order
* Paged
* Withdrawn
* Declared lost
2. *Item.status* and *item.status.name* are required now, no defaulting available anymore;
3. Array *item.copyNumbers* converted to a single value *copyNumber*;
4. Item.status.date is read-only field now and has date-time formatting now ("yyyy-MM-dd'T'HH:mm:ss.SSS+0000").
1. Array *request.item.copyNumbers* has converted to a single value - *copyNumber*;
2. *request/loan.item.status.date* has date-time formatting.
**Have to be …
=> SIP2-79: Migrate to circulation v10.0.

descriptors/ModuleDescriptor-template.json
Update dependencies due to new login interface version.
See https://issues.folio.org/browse/SIP2-84.
For additional context see https://issues.folio.org/browse/MODLOGIN-128 and related issues.
The breaking changes in mod-login were related to credential management, not the /authn/login API, so I think we can safely add 7.0 to the list of supported versions for the login interface.
=> SIP2-84 - compatible with login 7.0

Dockerfile, Jenkinsfile, pom.xml
Upgrade Edge-sip2 to use Java 11
I followed the pattern here on mod-rtac: https://github.com/folio-org/mod-rtac/commit/49d8a368baa96fce8876af90018145a09182049e.
=> SIP2-86: upgrade to Java 11

descriptors/ModuleDescriptor-template.json
As a result of breaking changes introduced in scope of [MODFEE-88](https://issues.folio.org/browse/MODFEE-88) major version of interface "feesfines" was updated from 15.6 to 16.0. Since SIP2 depends on this interface, it needs to adopt this change as well.
Endpoint `/manualblocks` used by SIP2 was not affected by changes in mod-feesfines.
=> [SIP2-88] Update version of interface "feesfines" to v16.0

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java, src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java, src/main/java/org/folio/edge/sip2/repositories/FeeFinesRepository.java, src/main/java/org/folio/edge/sip2/repositories/UsersRepository.java, src/main/java/org/folio/edge/sip2/utils/Utils.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java, src/test/java/org/folio/edge/sip2/utils/UtilsTests.java
URL encode the query strings for known API calls because Vert.x does not automatically encode them anymore.
=> SIP2-90: URL Encode Query Strings

descriptors/ModuleDescriptor-template.json
Resolves [SIP2-91](https://issues.folio.org/browse/SIP2-91)
Update `circulation` interface dependency to support version 10.0
=> SIP2-91 Update circulation interface dependency

descriptors/ModuleDescriptor-template.json
Resolves [SIP2-92](https://issues.folio.org/browse/SIP2-92).
There is a breaking change in `mod-circulaion` that will be merge soon. Modules that have a dependency on `circulation` interface need to be updated to support version `11.0`.
There are multiple PRs with `circulation` interface version update, they all should be merged on the same day. 
**DO NOT MERGE** this PR until then.
=> SIP2-92 Update circulation interface dependency

descriptors/ModuleDescriptor-template.json
Adapt the module to changed interface of mod-circulation from v12.0 to v13.0
Adapt ModuleDescriptor-template to circulation v13.0;
https://issues.folio.org/browse/SIP2-107
=> SIP2-107 Support circulation interface v13

pom.xml, src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/handlers/HandlersFactory.java, src/main/java/org/folio/edge/sip2/modules/FolioResourceProviderModule.java, src/main/java/org/folio/edge/sip2/parser/Parser.java, src/main/java/org/folio/edge/sip2/repositories/FolioResourceProvider.java, src/test/java/org/folio/edge/sip2/api/support/BaseTest.java, src/test/java/org/folio/edge/sip2/handlers/CheckinHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/CheckoutHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/EndPatronSessionHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/HandlersFactoryTests.java, src/test/java/org/folio/edge/sip2/handlers/LoginHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/PatronInformationHandlerTests.java, src/test/java/org/folio/edge/sip2/handlers/SCStatusHandlerTests.java, src/test/java/org/folio/edge/sip2/parser/ParserTests.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/ConfigurationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/DefaultResourceProviderTests.java, src/test/java/org/folio/edge/sip2/repositories/FeeFinesRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/FolioResourceProviderTests.java, src/test/java/org/folio/edge/sip2/repositories/LoginRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/PasswordVerifierTests.java, src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/UsersRepositoryTests.java
Update Vert.x from 3.9.* to 4.2.5.
Replace Vertx by WebClient for better re-use enabling
HTTP pooling and HTTP pipe-lining.
Use existing methods for random port.
=> SIP2-110: Update edge-sip2 to Vert.x 4.2.5

pom.xml
PR #78 has updated vertx-stack-depchain from 3.9.2 to 4.2.5, this has indirectly bumped netty from 4.1.49 to 4.1.72 fixing HTTP request smuggling: https://nvd.nist.gov/vuln/detail/CVE-2021-21295 and denial of service (DoS): https://nvd.nist.gov/vuln/detail/CVE-2021-37136 , https://nvd.nist.gov/vuln/detail/CVE-2021-37137
Update jackson from 2.10.2 to 2.11.4 by using the version from vertx-stack-depchain. This fixes an XML external entity (XXE) Injection: https://nvd.nist.gov/vuln/detail/CVE-2020-25649
Update freemarker from 2.3.28 to 2.3.31 fixing server-side template injection (SSTI): https://security.snyk.io/vuln/SNYK-JAVA-ORGFREEMARKER-1076795
Update guice from 4.2.3 to 5.1.0 fixing temp directory creation vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2020-8908
Update micrometer …
=> SIP2-110: Update dependencies (CVE-2020-25649)

src/main/java/org/folio/edge/sip2/domain/messages/requests/Checkin.java, src/main/java/org/folio/edge/sip2/domain/messages/requests/Checkout.java, src/main/java/org/folio/edge/sip2/domain/messages/requests/EndPatronSession.java, src/main/java/org/folio/edge/sip2/domain/messages/requests/Login.java, src/main/java/org/folio/edge/sip2/domain/messages/requests/PatronInformation.java, src/main/java/org/folio/edge/sip2/handlers/CheckinHandler.java, src/main/java/org/folio/edge/sip2/handlers/CheckoutHandler.java, src/main/java/org/folio/edge/sip2/handlers/EndPatronSessionHandler.java, src/main/java/org/folio/edge/sip2/handlers/LoginHandler.java, src/main/java/org/folio/edge/sip2/handlers/PatronInformationHandler.java, src/test/java/org/folio/edge/sip2/domain/messages/requests/CheckinTests.java, src/test/java/org/folio/edge/sip2/domain/messages/requests/CheckoutTests.java, src/test/java/org/folio/edge/sip2/domain/messages/requests/EndPatronSessionTests.java, src/test/java/org/folio/edge/sip2/domain/messages/requests/LoginTests.java, src/test/java/org/folio/edge/sip2/domain/messages/requests/PatronInformationTests.java
SIP2-124 ( https://issues.folio.org/browse/SIP2-124 ) 
#Purpose: 
- SIP2 log currently only logs sip response messages.
- When there are problems, I need to see the sip2 request that was made to troubleshoot the issue.
- May need to consider any requests containing potential sensitive information (such as passwords) - before logging
#Approach 
- Handler level logs now available 
- sensitive information is removed from logs
=> [SIP2-124] Logging improvement

README.md, descriptors/ModuleDescriptor-template.json
[SIP2-127] ( https://issues.folio.org/browse/SIP2-127 )
- Add missing permission automated-patron-blocks.collection.get in descriptor &  readme file for edge-sip.all permission set.
- Updated module-descriptor & Readme file 
- Created user in rancher with the following permissions 
- API used to add permission set details in readme.md file.
- Test against the item checkout API used with sip testing tool before and after the permission with the rancher environment.
=> [SIP2-127] - Adding missing permission in sip2.all permission set

NEWS.md, README.md, src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/handlers/RenewHandler.java, src/main/java/org/folio/edge/sip2/handlers/freemarker/FreemarkerRepository.java, src/main/java/org/folio/edge/sip2/modules/ApplicationModule.java, src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java, src/main/resources/templates/RenewResponse.ftl, src/test/java/org/folio/edge/sip2/domain/messages/requests/RenewTests.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java
The purpose of this ticket is to implement renew command in SIP2. https://issues.folio.org/browse/SIP2-121
Relevant code is added to handle the Renew an item command, which would handle the command to respond with renew response message as per the specifications laid down in 3M SIP2 document.
Renew command succeeded -- 
Renew command not succeeded --
=> [SIP2-121] - SIP2: Renew response

src/main/resources/templates/ItemInformationResponse.ftl, src/test/java/org/folio/edge/sip2/handlers/ItemInformationHandlerTests.java
The purpose of this PR is to cater to expectation laid down in SIP2-161 - Item Information Response is not formed as the standard is defined.  Only two of the three required 2-digits fields are actually exposed. It seems that security marker is not exposed. The hard coded default value 00 should be set for Security Marker.
Code changes made in itemInformationResposen.ftl file to default the value of Security Marker to 00.
- Are …
=> [SIP2-161] - Adding default security marker value 00 Other.

pom.xml, src/main/java/org/folio/edge/sip2/MainVerticle.java, src/main/java/org/folio/edge/sip2/utils/WebClientConfigException.java, src/main/java/org/folio/edge/sip2/utils/WebClientUtils.java, src/test/java/org/folio/edge/sip2/api/MainVerticleTests.java, src/test/java/org/folio/edge/sip2/utils/WebClientUtilsTests.java
Enable TLS on WebClient using certs and keys paths from the Json config
https://folio-org.atlassian.net/browse/SIP2-200
https://folio-org.atlassian.net/browse/SIP2-201
=> [SIP2-200-1] Enable TLS on WebClient

pom.xml
https://folio-org.atlassian.net/browse/SIP2-205
Dependency was added in scope of main SSL https://github.com/folio-org/edge-sip2/pull/164/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R194 only to avoid maven dependency plugin warning.
This dependency prevents application from starting, so has been deleted.
=> [SIP2-205] Issue with edge-sip2

src/main/java/org/folio/edge/sip2/repositories/CirculationRepository.java, src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java, src/main/java/org/folio/edge/sip2/utils/Utils.java, src/test/java/org/folio/edge/sip2/repositories/CirculationRepositoryTests.java, src/test/java/org/folio/edge/sip2/repositories/PatronRepositoryTests.java, src/test/java/org/folio/edge/sip2/utils/UtilsTests.java
https://folio-org.atlassian.net/browse/SIP2-257
- Fix an issue when only the first 10 charged were returned in response
- Adjust unit tests
- Increase default limit for `/circulation/loans` endpoint from 10 to 500
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> SIP2-257: Increase default fetch size for circulation loans

NEWS.md, src/main/java/org/folio/edge/sip2/domain/messages/enumerations/CurrencyType.java, src/main/java/org/folio/edge/sip2/parser/FeePaidMessageParser.java, src/main/java/org/folio/edge/sip2/repositories/ConfigurationRepository.java, src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java, src/test/java/org/folio/edge/sip2/parser/FeePaidMessageParserTest.java, src/test/java/org/folio/edge/sip2/parser/FeePaidMessageParserTests.java
Add an ability to parse new currency types in FeePaidMessageParser
- Replace switch manual currency iteration with more robust implementation
[SIP2-XXX](https://folio-org.atlassian.net/browse/SIP2-XXX)
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> SIP2-276: Fix missing currency values in FeePaidMessageParser

NEWS.md, pom.xml, src/main/java/org/folio/edge/sip2/integration/s3/S3ConfigStore.java, src/main/java/org/folio/edge/sip2/integration/s3/S3ConfigStoreFactory.java, src/main/resources/META-INF/services/io.vertx.config.spi.ConfigStoreFactory, src/main/resources/log4j2.xml, src/test/java/org/folio/edge/sip2/api/CheckInIT.java, src/test/java/org/folio/edge/sip2/api/EdgeSip2IT.java, src/test/java/org/folio/edge/sip2/api/S3ConfigIT.java, src/test/java/org/folio/edge/sip2/api/SipTlsEnabledIT.java, src/test/java/org/folio/edge/sip2/api/support/TestUtils.java, src/test/java/org/folio/edge/sip2/integration/s3/S3ConfigStoreFactoryTest.java, src/test/java/org/folio/edge/sip2/integration/s3/S3ConfigStoreTest.java, src/test/java/org/folio/edge/sip2/support/Sip2Commands.java, src/test/java/org/folio/edge/sip2/support/minio/EnableMinio.java, src/test/java/org/folio/edge/sip2/support/minio/MinioContainerExtension.java, src/test/java/org/folio/edge/sip2/support/model/CheckInCommand.java, src/test/java/org/folio/edge/sip2/support/model/Sip2MessageBuilder.java, src/test/java/org/folio/edge/sip2/support/wiremock/WiremockContainerExtension.java, src/test/resources/log4j2.xml, src/test/resources/wiremock/stubs/mod-circulation/200-get-open-circulation-requests-by-item-id.json, src/test/resources/wiremock/stubs/mod-circulation/201-check-in-by-barcode.json, src/test/resources/wiremock/stubs/mod-inventory/200-items-by-barcode.json
Replace the non-supported library with a folio-compliant `folio-s3-client` based configuration provider
- Replace non-supported library with a folio-compliant implementation
- Add integration test for config fetching from s3-compatible storage (MinIO)
- Extend integration tests from CheckIn command
[SIP2-294](https://folio-org.atlassian.net/browse/SIP2-294)
=> SIP2-294 Replace com.github.mikelee2082:vertx-config-s3 with folio-s3-client configuration
